export interface EntityData {
  [entity: string]: {
    [category: string]: string[]
  }
}

export const complaintData: EntityData = {
  Municipios: {
    "Alumbrado Público": [
      "Lámparas quemadas",
      "Falta de luminarias",
      "Luces encendidas de día",
      "Poste caído",
      "Cortocircuitos",
      "Iluminación insuficiente",
      "Problemas con faroles LED",
      "Cableado expuesto",
      "Intermitencias",
      "Reparaciones demoradas",
    ],
    "Recolección de Residuos": [
      "Retrasos en recolección",
      "Basura acumulada",
      "No se respeta cronograma",
      "Contenedores rotos",
      "Falta de contenedores",
      "Mal olor",
      "Residuos reciclables sin recoger",
      "Animales rompen bolsas",
      "Incumplimiento zonas rurales",
      "Recolección en días feriados",
    ],
    "Espacios Verdes": [
      "Falta de mantenimiento",
      "Pasto alto",
      "Juegos rotos",
      "Bancos dañados",
      "Basura en plazas",
      "Iluminación deficiente",
      "Riego insuficiente",
      "Arbolado seco",
      "Mal uso del espacio",
      "Vandalismo",
    ],
    "Seguridad Ciudadana": [
      "Poca presencia policial",
      "Cámaras sin funcionar",
      "Iluminación deficiente",
      "Zonas peligrosas",
      "Robos frecuentes",
      "Falta de patrullaje",
      "Alarmas comunitarias",
      "Venta de drogas",
      "Inseguridad escolar",
      "Problemas en eventos públicos",
    ],
    "Tránsito y Transporte": [
      "Semáforos sin funcionar",
      "Falta de señalización",
      "Calles mal pintadas",
      "Reductores peligrosos",
      "Baches",
      "Transporte público ineficiente",
      "Paradas sin techo",
      "Horarios incumplidos",
      "Multas mal aplicadas",
      "Mal estacionamiento",
    ],
  },
  Escuelas: {
    "Infraestructura Escolar": [
      "Baños rotos",
      "Filtraciones",
      "Ventanas rotas",
      "Calefacción/aire defectuoso",
      "Paredes agrietadas",
      "Techos con humedad",
      "Falta de mobiliario",
      "Conectividad limitada",
      "Puertas que no cierran",
      "Pisos peligrosos",
    ],
    "Equipamiento Tecnológico": [
      "Pizarras electrónicas sin funcionar",
      "Computadoras dañadas",
      "Falta de internet",
      "Proyector roto",
      "Tablets desactualizadas",
      "Software no licenciado",
      "Fallas en redes",
      "Conectores rotos",
      "Equipos sin mantenimiento",
      "Falta de soporte técnico",
    ],
    "Convivencia Escolar": [
      "Bullying",
      "Violencia entre estudiantes",
      "Falta de mediadores",
      "Discriminación",
      "Conflictos familiares",
      "Problemas con docentes",
      "Problemas en redes sociales",
      "Agresiones físicas",
      "Intimidaciones",
      "Ausencia de protocolos",
    ],
    "Comedor Escolar": [
      "Comida de baja calidad",
      "Mal estado de los alimentos",
      "Porciones pequeñas",
      "Horarios no adecuados",
      "Falta de cubiertos",
      "Comedores sucios",
      "Personal insuficiente",
      "Dietas especiales no respetadas",
      "Menús repetidos",
      "Incidentes sanitarios",
    ],
    "Calidad Educativa": [
      "Clases canceladas",
      "Contenidos poco actualizados",
      "Pocos docentes",
      "Falta de suplencias",
      "Materiales insuficientes",
      "Metodología inadecuada",
      "Baja motivación",
      "Evaluaciones mal diseñadas",
      "Falta de apoyo pedagógico",
      "No se respetan contenidos curriculares",
    ],
  },
  Clubes: {
    "Infraestructura Deportiva": [
      "Canchas en mal estado",
      "Iluminación deficiente",
      "Vestuarios deteriorados",
      "Duchas sin agua",
      "Falta de mantenimiento",
      "Equipamiento incompleto",
      "Techos con goteras",
      "Filtraciones",
      "Baños inhabilitados",
      "Alambrados rotos",
    ],
    "Actividades y Horarios": [
      "Horarios mal organizados",
      "Clases superpuestas",
      "Actividades canceladas",
      "Turnos mal asignados",
      "Capacidad colmada",
      "Falta de variedad",
      "Cambios sin aviso",
      "Poca inclusión",
      "Actividades no adaptadas",
      "Demoras en apertura",
    ],
    "Atención al Socio": [
      "Mal trato",
      "Procesos poco claros",
      "Problemas con cuotas",
      "No responden consultas",
      "Mal sistema de turnos",
      "No respetan prioridades",
      "Errores en inscripción",
      "Falta de comunicación",
      "No reconocen membresías",
      "Falta de beneficios",
    ],
    "Servicios Adicionales": [
      "Gimnasio con equipos rotos",
      "Piscina sucia",
      "Bar sin atención",
      "Faltan elementos de higiene",
      "Guardarropas sin control",
      "Poca limpieza",
      "Cerramientos peligrosos",
      "No hay primeros auxilios",
      "Falta de profesores",
      "No hay servicios para personas con discapacidad",
    ],
  },
  Cooperativas: {
    "Suministro Eléctrico": [
      "Cortes frecuentes",
      "Voltaje inestable",
      "Picos de tensión",
      "Equipos quemados",
      "Problemas con medidor",
      "Facturación incorrecta",
      "Mal servicio técnico",
      "Demoras en reconexión",
      "Cableado expuesto",
      "Poca respuesta ante emergencias",
    ],
    "Agua Potable": [
      "Falta de presión",
      "Agua turbia",
      "Olor desagradable",
      "Cortes sin aviso",
      "Filtraciones",
      "Problemas en medidor",
      "Tiempos de reparación largos",
      "Problemas con caños viejos",
      "Contaminación",
      "Exceso de cloro",
    ],
    "Internet/Telefonía": [
      "Velocidad baja",
      "Cortes frecuentes",
      "Facturación errónea",
      "Mal soporte técnico",
      "Router defectuoso",
      "No llegan técnicos",
      "No hay cobertura",
      "Problemas en fibra óptica",
      "Cambios sin aviso",
      "No actualizan equipos",
    ],
    "Atención al Usuario": [
      "No atienden reclamos",
      "Mal trato",
      "Largas esperas",
      "Errores en facturación",
      "Dificultades en oficina virtual",
      "Web no funciona",
      "Teléfonos sin respuesta",
      "Información confusa",
      "Poca empatía",
      "Derivan mal los casos",
    ],
  },
}

export const getEntities = (): string[] => {
  return Object.keys(complaintData)
}

export const getCategories = (entity: string): string[] => {
  return entity ? Object.keys(complaintData[entity] || {}) : []
}

export const getSubcategories = (entity: string, category: string): string[] => {
  return entity && category ? complaintData[entity]?.[category] || [] : []
}
