import type { Complaint } from "@/types/complaint"

export const mockComplaints: Complaint[] = [
  {
    id: "1",
    title: "Lámparas quemadas en Av. Principal",
    entity: "Municipios",
    category: "Alumbrado Público",
    subcategory: "Lámparas quemadas",
    description:
      "Hay varias lámparas quemadas en la Av. Principal entre las calles 5 y 8. La zona queda muy oscura por las noches y es peligroso caminar.",
    location: "Av. Principal entre calles 5 y 8",
    photo: "/broken-street-lights.png",
    authorId: "2",
    authorName: "María González",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    status: "open",
    votes: {
      positive: 12,
      negative: 2,
      userVotes: {},
    },
  },
  {
    id: "2",
    title: "Basura acumulada en Plaza Central",
    entity: "Municipios",
    category: "Recolección de Residuos",
    subcategory: "Basura acumulada",
    description:
      "La basura se acumula en la Plaza Central desde hace una semana. Los contenedores están desbordados y hay mal olor.",
    location: "Plaza Central",
    authorId: "3",
    authorName: "Carlos Rodríguez",
    createdAt: new Date("2024-01-14"),
    updatedAt: new Date("2024-01-14"),
    status: "open",
    votes: {
      positive: 8,
      negative: 1,
      userVotes: {},
    },
  },
  {
    id: "3",
    title: "Baños rotos en Escuela Primaria N°5",
    entity: "Escuelas",
    category: "Infraestructura Escolar",
    subcategory: "Baños rotos",
    description:
      "Los baños del segundo piso están fuera de servicio desde hace un mes. Los estudiantes deben usar los del primer piso.",
    location: "Escuela Primaria N°5",
    authorId: "1",
    authorName: "Cliente Test",
    createdAt: new Date("2024-01-13"),
    updatedAt: new Date("2024-01-13"),
    status: "open",
    votes: {
      positive: 15,
      negative: 0,
      userVotes: {},
    },
  },
  {
    id: "4",
    title: "Canchas en mal estado",
    entity: "Clubes",
    category: "Infraestructura Deportiva",
    subcategory: "Canchas en mal estado",
    description:
      "Las canchas de tenis tienen grietas y la superficie está muy deteriorada. Es peligroso jugar en estas condiciones.",
    location: "Club Deportivo Central",
    authorId: "4",
    authorName: "Ana López",
    createdAt: new Date("2024-01-12"),
    updatedAt: new Date("2024-01-12"),
    status: "open",
    votes: {
      positive: 6,
      negative: 3,
      userVotes: {},
    },
  },
  {
    id: "5",
    title: "Cortes frecuentes de luz",
    entity: "Cooperativas",
    category: "Suministro Eléctrico",
    subcategory: "Cortes frecuentes",
    description:
      "En el barrio San Martín hay cortes de luz casi todos los días. Afecta el trabajo desde casa y los electrodomésticos.",
    location: "Barrio San Martín",
    authorId: "1",
    authorName: "Cliente Test",
    createdAt: new Date("2024-01-11"),
    updatedAt: new Date("2024-01-11"),
    status: "closed",
    votes: {
      positive: 20,
      negative: 1,
      userVotes: {},
    },
  },
]
